#!/bin/bash

dots_dir=$(cat $HOME/.dotsconfig)
files=$(ls -a $dots_dir | grep -Ev '^\.$|^\.\.$|^.git*|^README.md$|^other$')

# shows usage
usage () {
    echo "usage: dots [set <path>] [link] [status]"
}

# check if file is linked
linked () {
    [ -h $HOME/.config/$1 ] || [ -h $HOME/$1 ]
}

# shows status for dotfiles
status () {
    for file in $files; do
        if linked $file; then
            echo -e "$(tput bold)\e[36m$file\e[0m@"
        else
            echo $file
        fi
    done
}

# contains all possible commands
case $1 in
    link)
        if [ ! $2 ]; then
            for file in $files; do
                if ! linked $file; then
                    if [ -d $dots_dir/$file ] && [[ ! $file = .* ]]; then
                        ln -s $dots_dir/$file $HOME/.config/ && echo "linked $HOME/.config/$file"
                    elif [[ $file = .* ]]; then
                        ln -s $dots_dir/$file $HOME/ && echo "linked $HOME/$file"
                    fi
                fi
            done
            echo "done!"
        else
            file="$2"
            if [ -d $dots_dir/$file ] && [[ ! $file = .* ]]; then
                ln -s $dots_dir/$file $HOME/.config/ && echo "linked $HOME/.config/$file"
            elif [[ $file = .* ]]; then
                ln -s $dots_dir/$file $HOME/ && echo "linked $HOME/$file"
            fi
        fi
    ;;

    set)
        if [ $2 ]; then
            echo $2 > $HOME/.dotsconfig
        else
            echo "missing argument"
        fi
    ;;

    status)
        status
    ;;

    *)
        usage
    ;;
esac
