#!/bin/bash

DOTS_DIR="${DOTS_DIR:-$HOME/.dotfiles}"

if [ ! -d $DOTS_DIR ]; then
    echo "directory does not exist: $DOTS_DIR"
    exit 1
fi

files=$(ls -a $DOTS_DIR | grep -Ev '^\.$|^\.\.$|^.git*|^README.md$|^other$')

NO_FORMAT="\033[0m"
F_BOLD="\033[1m"
C_LIME="\033[38;5;10m"
C_RED="\033[38;5;9m"

# shows usage
usage () {
    echo "usage: dots [set <path>] [link] [status]"
}

# check if file is linked
linked () {
    [ -h $HOME/.config/$1 ] || [ -h $HOME/$1 ]
}

# shows status for dotfiles
status () {
    echo "Dotfiles in $DOTS_DIR$([ $DOTS_DIR == $HOME/.dotfiles ] && echo ' (default)')"

    echo -e "\nFiles linked:"
    for file in $files; do
        if linked $file; then
            echo -e "    ${C_LIME}$file${NO_FORMAT}"
        fi
    done

    echo -e "\nFiles unlinked:"
    for file in $files; do
        if ! linked $file; then
            echo -e "    ${C_RED}$file${NO_FORMAT}"
        fi
    done
}

# link a dotfile
link () {
    if [ -d $DOTS_DIR/$1 ] && [[ ! $1 = .* ]]; then
        ln -s $DOTS_DIR/$1 $HOME/.config/ && echo "created link at $HOME/.config/$1"
    elif [[ $1 = .* ]]; then
        ln -s $DOTS_DIR/$1 $HOME/ && echo "created link at $HOME/$1"
    fi
}

# unlink a dotfile
rmlink () {
    if [ -d $DOTS_DIR/$1 ] && [[ ! $1 = .* ]]; then
        unlink $HOME/.config/$1 && echo "unlinked $HOME/.config/$1"
    elif [[ $1 = .* ]]; then
        unlink $HOME/$1 && echo "unlinked $HOME/$1"
    fi
}

# contains all possible commands
case $1 in
    link | l)
        if [ ! $2 ]; then
            for file in $files; do
                if ! linked $file; then
                    link $file
                fi
            done
            echo "done!"
        else
            link $2
        fi
    ;;

    unlink | ul)
        if [ ! $2 ]; then
            for file in $files; do
                if linked $file; then
                    rmlink $file
                fi
            done
            echo "done!"
        else
            rmlink $2
        fi
    ;;

    set)
        if [ $2 ]; then
            echo $2 > $HOME/.dotsconfig
        else
            echo "missing argument"
        fi
    ;;

    status | list | ls)
        status
    ;;

    *)
        usage
    ;;
esac
